### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-1-Mushik** [UMSF-K13-1-Mushik/Project#1]
[K13-1-Mushik.docx](https://github.com/UMSF-K13-1-Mushik/Project/files/288308/K13-1-Mushik.docx)

**Comment by Smoktii** [comment]
Установите меня как исполнителя ишью

**Comment by UMSF-K13-1-Mushik** [comment]
сделал

**Comment by Smoktii** [comment]
ок
